name: Release Chromium Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 14 * * 0-6"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        sudo apt update
        sudo apt install libfuse2
        wget https://raw.githubusercontent.com/ouyen/Chromium-Web-Browser-appimage/main/chromium -O build.sh
        chmod a+x ./build.sh
        ./build.sh
        mkdir dist
        mv *AppImage dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Chromium-Web-Browser-x86_64.AppImage
        path: 'dist'
        
  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: Chromium-Web-Browser-x86_64.AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              Chromium-Web-Browser-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
